CREATE TABLE usuario(
	dni INT(8) UNSIGNED NOT NULL,
	pass CHAR(128) NOT NULL, # SHA512
	email VARCHAR(50) NOT NULL,
	nombre VARCHAR(20) NOT NULL,
	apellido VARCHAR(20) NOT NULL,
	telefono INT(11) UNSIGNED NOT NULL,
	es_profe BOOLEAN NOT NULL DEFAULT 0,
	urlImg VARCHAR(50) NULL,
	sexo BOOLEAN NOT NULL,
	PRIMARY KEY (dni) USING HASH,
	UNIQUE (telefono) USING HASH
) ENGINE = InnoDB;

CREATE TABLE profesor(
	dni INT(8) UNSIGNED NOT NULL,
    PRIMARY KEY(dni)
) ENGINE = InnoDB;

CREATE TABLE estudiante (
	dni INT(8) UNSIGNED NOT NULL,
    PRIMARY KEY(dni)
) ENGINE = InnoDB;

CREATE TABLE curso(
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	nombre VARCHAR(20) NOT NULL,
	descripcion VARCHAR(500) NULL,
	anuncio VARCHAR(300) NULL,
	PRIMARY KEY (id)
) ENGINE = InnoDB;

CREATE TABLE clase (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	titulo VARCHAR(30) NOT NULL,
	curso INT UNSIGNED NOT NULL,
	video VARCHAR(15) NOT NULL,
	fecha DATE NOT NULL,
	duracion INT UNSIGNED NOT NULL,
	PRIMARY KEY (id),
	UNIQUE clase (curso, video) USING BTREE
) ENGINE = InnoDB;

CREATE TABLE participantes(
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	estudiante INT(8) UNSIGNED NOT NULL,
	curso INT UNSIGNED NOT NULL,
	progreso INT UNSIGNED NOT NULL DEFAULT 0,
	ultimo_visto VARCHAR(15) NOT NULL,
	anuncio BOOLEAN NOT NULL DEFAULT 1,
	PRIMARY KEY(id)
) ENGINE = InnoDB;

CREATE TABLE vistos (
	estudiante INT(8) UNSIGNED NOT NULL,
	curso INT UNSIGNED NOT NULL,
	clase INT UNSIGNED NOT NULL,
	visto BOOLEAN NOT NULL DEFAULT 0,
    PRIMARY KEY(estudiante, clase)
) ENGINE = InnoDB;

-- Claves extranjeras

ALTER TABLE profesor
	ADD CONSTRAINT fk_profesor_usuario
	FOREIGN KEY (dni) REFERENCES usuario(dni)
	ON DELETE RESTRICT ON UPDATE CASCADE
;
ALTER TABLE estudiante
	ADD CONSTRAINT fk_estudiante_usuario
	FOREIGN KEY (dni) REFERENCES usuario(dni)
	ON DELETE RESTRICT ON UPDATE CASCADE
;
ALTER TABLE clase
	ADD CONSTRAINT fk_clases_curso
	FOREIGN KEY (curso) REFERENCES curso(id)
	ON DELETE CASCADE ON UPDATE CASCADE
;
ALTER TABLE participantes
	ADD CONSTRAINT fk_participantes_estudiante
	FOREIGN KEY (estudiante) REFERENCES estudiante(dni)
	ON DELETE RESTRICT ON UPDATE CASCADE
;
ALTER TABLE participantes
	ADD CONSTRAINT fk_participantes_curso
	FOREIGN KEY (curso) REFERENCES curso(id)
	ON DELETE RESTRICT ON UPDATE CASCADE
;
ALTER TABLE vistos
	ADD CONSTRAINT fk_vistos_estudiante
	FOREIGN KEY (estudiante) REFERENCES estudiante(dni)
	ON DELETE CASCADE ON UPDATE CASCADE
;
ALTER TABLE vistos
	ADD CONSTRAINT fk_vistos_clase
	FOREIGN KEY (clase) REFERENCES clase(id)
	ON DELETE CASCADE ON UPDATE CASCADE
;
ALTER TABLE vistos
	ADD CONSTRAINT fk_vistos_curso
	FOREIGN KEY (curso) REFERENCES curso(id)
	ON DELETE CASCADE ON UPDATE CASCADE
;